// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://huxpllhtbxwplohpqwvi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh1eHBsbGh0Ynh3cGxvaHBxd3ZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzNTE5NDEsImV4cCI6MjA2NTkyNzk0MX0.XuDEX0urIanrerTV5T1UmtV-FJPIIXPsrUGD2T4kwMY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);